/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "magic_code.h"

void *
magic_code_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
    printf("Remote procedure called now =====\n");
    printf("Remote procedure called \n");

	return (void *) &result;
}
