/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAGIC_CODE_H_RPCGEN
#define _MAGIC_CODE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define MAGIC_CODE_PROG 0x23451111
#define MAGIC_CODE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define magic_code 1
extern  int * magic_code_1(char **, CLIENT *);
extern  int * magic_code_1_svc(char **, struct svc_req *);
extern int magic_code_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define magic_code 1
extern  int * magic_code_1();
extern  int * magic_code_1_svc();
extern int magic_code_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAGIC_CODE_H_RPCGEN */
